In [1]:
import pandas as pd

In [2]:
def my_function():
    #indent 4 spaces or tab
    print('john')

In [3]:
my_function()

john


In [14]:
def my_sq(x):
    # """ """ signifies documentation string
    """
    squares a value (x) where x is any variable
    
    parameters
    -----------
    x: value to square
    
    returns
    -----------
    squared value
    
    """
    
    #print(x)
    # print in beginning to troubleshoot, once errors are eliminated can delete print prompt, or hashtag (comment) out
    return x ** 2

In [15]:
my_sq(10)

100

In [16]:
output = my_sq(10)

In [17]:
output

100

In [18]:
?my_sq

Signature: my_sq(x)
Docstring:
squares a value (x) where x is any variable

parameters
-----------
x: value to square

returns
-----------
squared value
File:      ~/git/teaching/2020-python_john/class/<ipython-input-14-d32a1f0cb629>
Type:      function


In [19]:
def avg_2(x,y):
    """calculates the average between 2 numbers """
    return (x+y)/2

In [20]:
avg_2(10,50)

30.0

In [21]:
df = pd.DataFrame({
    'a': [10,20,30],
    'b': [20,30,40]})

In [22]:
df

a   b
0  10  20
1  20  30
2  30  40

In [23]:
df['a']

0    10
1    20
2    30
Name: a, dtype: int64

In [24]:
df['a']**2

0    100
1    400
2    900
Name: a, dtype: int64

In [25]:
df['a'].apply(my_sq)

0    100
1    400
2    900
Name: a, dtype: int64

In [32]:
def my_exp(x,e=10):
    return x ** e

In [33]:
my_exp(4,5)

1024

In [34]:
df['a'].apply(my_exp)

0        10000000000
1     10240000000000
2    590490000000000
Name: a, dtype: int64

In [35]:
df['a'].apply(my_exp, e=3)

0     1000
1     8000
2    27000
Name: a, dtype: int64

In [36]:
# df['c'] = df['a'].apply(my_exp, e=2)

In [37]:
def print_me(x):
    print(x)

In [40]:
print_me(54321)

54321


In [41]:
df.apply(print_me)

0    10
1    20
2    30
Name: a, dtype: int64
0    20
1    30
2    40
Name: b, dtype: int64


a    None
b    None
dtype: object

In [43]:
def avg_3(x, y, z):
    return (x + y + z)/3

In [44]:
avg_3(2,4,6)

4.0

In [45]:
df.apply(avg_3)

TypeError: avg_3() missing 2 required positional arguments: 'y' and 'z'

In [46]:
def avg_3_apply(col):
    x = col[0]
    y = col[1]
    z = col[2]
    return (x + y + z)/3

In [47]:
df.apply(avg_3_apply)

a    20.0
b    30.0
dtype: float64

In [48]:
df.apply(avg_3_apply,1)

IndexError: index 2 is out of bounds for axis 0 with size 2

In [49]:
# above errored because (1 signifies rows), rows does not have enough inputs

In [50]:
df

a   b
0  10  20
1  20  30
2  30  40

In [51]:
import numpy as np

In [53]:
def avg_2_mod(x , y):
    if (x == 20):
        return np.NaN #can type nan, NAN or NaN
    else:
        return (x + y)/2

In [54]:
avg_2_mod_vec = np.vectorize(avg_2_mod)

In [55]:
avg_2_mod_vec(df['a'], df['b'])

array([15., nan, 35.])

In [61]:
@np.vectorize # vectorize function to eliminate having to run vectorize ... this is called a decorator
def v_avg_2_mod(x , y):
    if (x == 20):
        return np.NaN #can type nan, NAN or NaN
    else:
        return (x + y)/2

In [63]:
v_avg_2_mod(df['a'], df['b'])

array([15., nan, 35.])

In [64]:
import numba as nb

In [65]:
@nb.vectorize # vectorzie using numba i/o numpy
def v_avg_2_mod_numba(x , y):
    if (x == 20):
        return np.NaN #can type nan, NAN or NaN
    else:
        return (x + y)/2

In [67]:
v_avg_2_mod_numba(df['a'].values, df['b'].values)

array([15., nan, 35.])

In [68]:
%%timeit
avg_2(df['a'], df['b'])

232 µs ± 6.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [69]:
%%timeit
v_avg_2_mod(df['a'],df['b'])

61.2 µs ± 731 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [70]:
%%timeit
v_avg_2_mod_numba(df['a'].values, df['b'].values)

5.63 µs ± 22.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
